#!/usr/bin/env node

const X2JS = require("x2js");
const fs = require("fs");

const argOne = process.argv[2];
const argTwo = argOne.slice(0, argOne.length - 4) + "0.json"


let x2js = new X2JS()


let xmlFile = fs.readFileSync(argOne).toString()

let document = x2js.xml2js(xmlFile);
let jsonString = JSON.stringify(document)


fs.writeFile(argTwo, jsonString, err => {
    if (err) {
        console.error(err)
        return
    }
//file written successfully
})